# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    build: app
    restart: always
    environment:
      BZ_WEB_PORT: 5000
      BZ_API_VERSION: 1.0.0.0
      BZ_APP_NAME: 'Being Zero Dockerized App'
    ports:
      - "5000:5000"
    networks:
    - beingzero
  
networks:
  beingzero: